### ISSUE TITLE
Where is the dl button

### ISSUE THREAD

**Issue by sant3e** [filipsch/dvd-rentals#1]
As i said during the online meeting.. I don't have ANY download zip button... So, how do I dl the zip file?

**Comment by filipsch** [comment]
It's right here!

![image](https://user-images.githubusercontent.com/5768479/135889725-2d555d43-5b42-4aa5-978b-db2bd41ff96f.png)

**Comment by sant3e** [comment]
I'm not getting the same stuff as you...when i press code i don't have any of your buttonsSent from my Galaxy
-------- Original message --------From: Filip Schouwenaars ***@***.***> Date: 04/10/2021  19:35  (GMT+02:00) To: filipsch/dvd-rentals ***@***.***> Cc: sant3e ***@***.***>, Author ***@***.***> Subject: Re: [filipsch/dvd-rentals] Where is the dl button (#1) 
It's right here!

**Comment by filipsch** [comment]
Hi @sant3e this may be because you're on mobile? Or because you're not logged in? The rate limiting should no longer be a problem, so you can just create the workspace from the "GitHub repository" button from the DataCamp Workspace 
dashboard.
